## Chinook database
![Chinook Schema](https://s3.amazonaws.com/dq-content/191/chinook-schema.svg)

### Connect jupyter notebook to the databse

In [1]:
%%capture
%load_ext sql
%sql sqlite:///chinook.db

'Connected: None@chinook.db'

### Explore table and views

In [2]:
%%sql
SELECT
    name, 
    Type
FROM sqlite_master
WHERE type IN ("table", "view");

Done.

[('album', 'table'),
 ('artist', 'table'),
 ('customer', 'table'),
 ('employee', 'table'),
 ('genre', 'table'),
 ('invoice', 'table'),
 ('invoice_line', 'table'),
 ('media_type', 'table'),
 ('playlist', 'table'),
 ('playlist_track', 'table'),
 ('track', 'table')]

### Number of records sold for each genre in USA

In [3]:
%%sql
With track_invoice AS
(
    SELECT g.name, il.quantity 
        FROM track t
        INNER JOIN invoice_line il
        ON t.track_id = il.track_id
        INNER JOIN invoice i
        ON i.invoice_id = il.invoice_id
        INNER JOIN genre g
        ON g.genre_id = t.genre_id
        WHERE i.billing_country = "USA"
)
SELECT 
    name, 
    sum(quantity) as num_of_tracks
FROM track_invoice
GROUP BY name
ORDER BY num_of_tracks DESC;

Done.

[('Rock', 561),
 ('Alternative & Punk', 130),
 ('Metal', 124),
 ('R&B/Soul', 53),
 ('Blues', 36),
 ('Alternative', 35),
 ('Latin', 22),
 ('Pop', 22),
 ('Hip Hop/Rap', 20),
 ('Jazz', 14),
 ('Easy Listening', 13),
 ('Reggae', 6),
 ('Electronica/Dance', 5),
 ('Classical', 4),
 ('Heavy Metal', 3),
 ('Soundtrack', 2),
 ('TV Shows', 1)]

Rock, Alternative & Punk, Metal, R&B/Soul and Blues are the top 5 mostly sold genre in the USA.
Artist Name	Genre
Regal	Hip-Hop
Red Tone	Punk
Meteor and the Girls	Pop
Slim Jim Bites	Blues
So for the above new albums, Slim Jim Bites is expected to perfrom much better in USA than other artists

Total dollar amount of sales assigned to each sales support agent within the company

In [4]:
%%sql
With employee_sales AS
(
    SELECT e.first_name, e.last_name, i.total
        FROM employee e
            LEFT JOIN
                customer c ON e.employee_id = support_rep_id
                    LEFT JOIN
                        invoice i ON i.customer_id = c.customer_id
)
SELECT 
    first_name || " " || last_name AS name,
    sum(total) as sales_made
FROM employee_sales
GROUP BY name
ORDER BY sales_made DESC;

Done.

[('Jane Peacock', 1731.510000000004),
 ('Margaret Park', 1584.0000000000032),
 ('Steve Johnson', 1393.9200000000028),
 ('Andrew Adams', None),
 ('Laura Callahan', None),
 ('Michael Mitchell', None),
 ('Nancy Edwards', None),
 ('Robert King', None)]

Jane Peacock, Margaret Park and Steve Johnson are only employees who were able to make sales while others were unable to make sales. Jane is the most hard workign eployee.

In [14]:
%%sql

WITH customer_invoice 
    AS (
        SELECT * 
        FROM customer c
        LEFT JOIN 
            (
                SELECT customer_id, sum(total) as total,
                avg(total) as avg_order
                FROM invoice
                GROUP BY customer_id
            )
        i ON c.customer_id = i.customer_id
    )
SELECT 
    new_country,
    sum(num) as total_customer,
    sum(total) as total_sales,
    total/num as avg_sales_per_customer,
    avg(avg_order) as avg_order
    FROM
    (
    SELECT
        CASE WHEN num = 1 THEN 'Other'
            ELSE country end AS new_country,
            num, total, avg_order
        FROM
            (
                SELECT country, 
                    count(*) as num,
                    sum(total) as total,
                    avg(avg_order) as avg_order
                    FROM customer_invoice
                    GROUP BY country
            )
    )
    GROUP BY new_country
    ORDER BY CASE WHEN num = 1 then 0
    ELSE 1 END DESC, total_sales DESC;

Done.

[('USA', 13, 1040.49, 80.03769230769231, 8.014750000000001),
 ('Canada', 8, 535.59, 66.94875, 7.416237980769231),
 ('Brazil', 5, 427.67999999999995, 85.53599999999999, 6.987484615384615),
 ('France', 5, 389.07, 77.814, 7.834999999999998),
 ('Germany', 4, 334.62, 83.655, 8.18875),
 ('Czech Republic', 2, 273.24, 136.62, 9.377500000000001),
 ('United Kingdom', 3, 245.51999999999998, 81.83999999999999, 8.749583333333334),
 ('Portugal', 2, 185.13, 92.565, 6.5278125000000005),
 ('India', 2, 183.14999999999998, 91.57499999999999, 8.757692307692308),
 ('Other', 15, 1094.9399999999998, 75.24, 7.445071062271063)]

There are more customers in USA but this also shows the fact that the per person spending is less in India

In [17]:
%%sql
SELECT *
    FROM invoice_line
    LIMIT 5;

Done.

[(1, 1, 1158, 0.99, 1),
 (2, 1, 1159, 0.99, 1),
 (3, 1, 1160, 0.99, 1),
 (4, 1, 1161, 0.99, 1),
 (5, 1, 1162, 0.99, 1)]

In [25]:
%%sql
SELECT invoice_id,
    COUNT(DISTINCT track_id) as invoice_track_num
    FROM invoice_line
    GROUP BY invoice_id;

Done.

[(1, 16),
 (2, 10),
 (3, 2),
 (4, 8),
 (5, 17),
 (6, 2),
 (7, 11),
 (8, 10),
 (9, 9),
 (10, 2),
 (11, 11),
 (12, 4),
 (13, 1),
 (14, 1),
 (15, 4),
 (16, 9),
 (17, 11),
 (18, 5),
 (19, 7),
 (20, 9),
 (21, 9),
 (22, 2),
 (23, 10),
 (24, 12),
 (25, 8),
 (26, 2),
 (27, 8),
 (28, 3),
 (29, 6),
 (30, 11),
 (31, 20),
 (32, 13),
 (33, 4),
 (34, 1),
 (35, 5),
 (36, 7),
 (37, 10),
 (38, 7),
 (39, 8),
 (40, 10),
 (41, 8),
 (42, 9),
 (43, 7),
 (44, 12),
 (45, 8),
 (46, 11),
 (47, 6),
 (48, 4),
 (49, 4),
 (50, 7),
 (51, 8),
 (52, 12),
 (53, 3),
 (54, 18),
 (55, 10),
 (56, 17),
 (57, 1),
 (58, 6),
 (59, 11),
 (60, 8),
 (61, 12),
 (62, 3),
 (63, 6),
 (64, 13),
 (65, 2),
 (66, 7),
 (67, 11),
 (68, 11),
 (69, 14),
 (70, 1),
 (71, 17),
 (72, 3),
 (73, 15),
 (74, 2),
 (75, 4),
 (76, 13),
 (77, 6),
 (78, 9),
 (79, 14),
 (80, 1),
 (81, 6),
 (82, 7),
 (83, 4),
 (84, 12),
 (85, 5),
 (86, 1),
 (87, 8),
 (88, 5),
 (89, 2),
 (90, 11),
 (91, 11),
 (92, 20),
 (93, 10),
 (94, 8),
 (95, 11),
 (96, 6),
 (97, 6),
 (98, 10),
 (99, 18),
 (100, 6),
 (101, 4),
 (102, 10),
 (103, 6),
 (104, 2),
 (105, 8),
 (106, 8),
 (107, 11),
 (108, 5),
 (109, 11),
 (110, 6),
 (111, 5),
 (112, 17),
 (113, 10),
 (114, 17),
 (115, 9),
 (116, 11),
 (117, 11),
 (118, 1),
 (119, 2),
 (120, 6),
 (121, 9),
 (122, 5),
 (123, 12),
 (124, 6),
 (125, 10),
 (126, 4),
 (127, 11),
 (128, 7),
 (129, 11),
 (130, 4),
 (131, 3),
 (132, 2),
 (133, 10),
 (134, 8),
 (135, 3),
 (136, 4),
 (137, 2),
 (138, 11),
 (139, 5),
 (140, 8),
 (141, 18),
 (142, 15),
 (143, 5),
 (144, 3),
 (145, 5),
 (146, 13),
 (147, 5),
 (148, 9),
 (149, 9),
 (150, 3),
 (151, 3),
 (152, 6),
 (153, 14),
 (154, 3),
 (155, 9),
 (156, 11),
 (157, 1),
 (158, 6),
 (159, 6),
 (160, 9),
 (161, 8),
 (162, 9),
 (163, 9),
 (164, 4),
 (165, 8),
 (166, 10),
 (167, 6),
 (168, 6),
 (169, 9),
 (170, 10),
 (171, 13),
 (172, 8),
 (173, 11),
 (174, 7),
 (175, 18),
 (176, 7),
 (177, 2),
 (178, 3),
 (179, 10),
 (180, 10),
 (181, 7),
 (182, 6),
 (183, 24),
 (184, 1),
 (185, 9),
 (186, 3),
 (187, 7),
 (188, 11),
 (189, 4),
 (190, 5),
 (191, 4),
 (192, 9),
 (193, 2),
 (194, 1),
 (195, 11),
 (196, 10),
 (197, 11),
 (198, 11),
 (199, 3),
 (200, 8),
 (201, 12),
 (202, 2),
 (203, 10),
 (204, 11),
 (205, 10),
 (206, 5),
 (207, 4),
 (208, 6),
 (209, 4),
 (210, 11),
 (211, 9),
 (212, 12),
 (213, 11),
 (214, 5),
 (215, 2),
 (216, 5),
 (217, 10),
 (218, 9),
 (219, 3),
 (220, 9),
 (221, 8),
 (222, 2),
 (223, 18),
 (224, 9),
 (225, 6),
 (226, 11),
 (227, 10),
 (228, 4),
 (229, 3),
 (230, 8),
 (231, 3),
 (232, 4),
 (233, 6),
 (234, 1),
 (235, 7),
 (236, 3),
 (237, 16),
 (238, 10),
 (239, 16),
 (240, 3),
 (241, 2),
 (242, 10),
 (243, 11),
 (244, 5),
 (245, 3),
 (246, 9),
 (247, 11),
 (248, 7),
 (249, 2),
 (250, 11),
 (251, 7),
 (252, 8),
 (253, 12),
 (254, 10),
 (255, 4),
 (256, 5),
 (257, 11),
 (258, 1),
 (259, 7),
 (260, 8),
 (261, 7),
 (262, 8),
 (263, 5),
 (264, 1),
 (265, 7),
 (266, 6),
 (267, 2),
 (268, 11),
 (269, 1),
 (270, 11),
 (271, 11),
 (272, 9),
 (273, 17),
 (274, 5),
 (275, 8),
 (276, 19),
 (277, 5),
 (278, 3),
 (279, 5),
 (280, 11),
 (281, 14),
 (282, 17),
 (283, 9),
 (284, 11),
 (285, 10),
 (286, 2),
 (287, 2),
 (288, 11),
 (289, 7),
 (290, 5),
 (291, 3),
 (292, 10),
 (293, 5),
 (294, 11),
 (295, 1),
 (296, 13),
 (297, 3),
 (298, 9),
 (299, 6),
 (300, 12),
 (301, 8),
 (302, 4),
 (303, 10),
 (304, 7),
 (305, 15),
 (306, 11),
 (307, 10),
 (308, 11),
 (309, 9),
 (310, 9),
 (311, 6),
 (312, 10),
 (313, 5),
 (314, 10),
 (315, 5),
 (316, 2),
 (317, 12),
 (318, 8),
 (319, 10),
 (320, 17),
 (321, 1),
 (322, 10),
 (323, 8),
 (324, 5),
 (325, 10),
 (326, 9),
 (327, 9),
 (328, 4),
 (329, 1),
 (330, 13),
 (331, 6),
 (332, 10),
 (333, 6),
 (334, 15),
 (335, 15),
 (336, 16),
 (337, 10),
 (338, 5),
 (339, 8),
 (340, 3),
 (341, 12),
 (342, 3),
 (343, 6),
 (344, 17),
 (345, 10),
 (346, 6),
 (347, 4),
 (348, 9),
 (349, 1),
 (350, 3),
 (351, 10),
 (352, 1),
 (353, 9),
 (354, 5),
 (355, 7),
 (356, 7),
 (357, 3),
 (358, 7),
 (359, 9),
 (360, 4),
 (361, 2),
 (362, 20),
 (363, 3),
 (364, 6),
 (365, 4),
 (366, 9),
 (367, 8),
 (368, 2),
 (369, 10),
 (370, 9),
 (371, 1),
 (372, 14),
 (373, 4),
 (374, 6),
 (375, 9),
 (376, 4),
 (377, 3),
 (378, 4),
 (379, 12),
 (380, 10),
 (381, 13),
 (382, 4),
 (383, 10),
 (384, 11),
 (385, 7),
 (386, 5),
 (387, 6),
 (388, 10),
 (389, 17),
 (390, 3),
 (391, 4),
 (392, 8),
 (393, 11),
 (394, 8),
 (395, 10),
 (396, 9),
 (397, 7),
 (398, 17),
 (399, 12),
 (400, 4),
 (401, 9),
 (402, 9),
 (403, 9),
 (404, 14),
 (405, 8),
 (406, 2),
 (407, 10),
 (408, 6),
 (409, 11),
 (410, 4),
 (411, 2),
 (412, 8),
 (413, 15),
 (414, 10),
 (415, 9),
 (416, 1),
 (417, 10),
 (418, 1),
 (419, 10),
 (420, 10),
 (421, 7),
 (422, 7),
 (423, 11),
 (424, 2),
 (425, 1),
 (426, 4),
 (427, 15),
 (428, 4),
 (429, 11),
 (430, 2),
 (431, 10),
 (432, 2),
 (433, 3),
 (434, 10),
 (435, 6),
 (436, 6),
 (437, 10),
 (438, 11),
 (439, 7),
 (440, 3),
 (441, 7),
 (442, 4),
 (443, 8),
 (444, 9),
 (445, 4),
 (446, 9),
 (447, 11),
 (448, 10),
 (449, 17),
 (450, 7),
 (451, 1),
 (452, 8),
 (453, 5),
 (454, 15),
 (455, 5),
 (456, 9),
 (457, 15),
 (458, 1),
 (459, 2),
 (460, 11),
 (461, 8),
 (462, 9),
 (463, 12),
 (464, 4),
 (465, 7),
 (466, 4),
 (467, 10),
 (468, 16),
 (469, 1),
 (470, 2),
 (471, 1),
 (472, 3),
 (473, 4),
 (474, 7),
 (475, 8),
 (476, 11),
 (477, 7),
 (478, 17),
 (479, 17),
 (480, 10),
 (481, 4),
 (482, 8),
 (483, 5),
 (484, 3),
 (485, 10),
 (486, 9),
 (487, 10),
 (488, 14),
 (489, 3),
 (490, 9),
 (491, 2),
 (492, 5),
 (493, 4),
 (494, 10),
 (495, 1),
 (496, 8),
 (497, 7),
 (498, 4),
 (499, 10),
 (500, 9),
 (501, 13),
 (502, 4),
 (503, 10),
 (504, 11),
 (505, 1),
 (506, 16),
 (507, 1),
 (508, 9),
 (509, 7),
 (510, 10),
 (511, 7),
 (512, 9),
 (513, 11),
 (514, 3),
 (515, 3),
 (516, 2),
 (517, 8),
 (518, 2),
 (519, 7),
 (520, 10),
 (521, 4),
 (522, 8),
 (523, 8),
 (524, 5),
 (525, 10),
 (526, 20),
 (527, 11),
 (528, 16),
 (529, 14),
 (530, 1),
 (531, 12),
 (532, 14),
 (533, 13),
 (534, 6),
 (535, 1),
 (536, 6),
 (537, 8),
 (538, 9),
 (539, 1),
 (540, 11),
 (541, 3),
 (542, 11),
 (543, 3),
 (544, 9),
 (545, 8),
 (546, 7),
 (547, 10),
 (548, 11),
 (549, 11),
 (550, 10),
 (551, 11),
 (552, 6),
 (553, 5),
 (554, 9),
 (555, 2),
 (556, 11),
 (557, 10),
 (558, 11),
 (559, 6),
 (560, 9),
 (561, 7),
 (562, 9),
 (563, 2),
 (564, 6),
 (565, 10),
 (566, 5),
 (567, 8),
 (568, 7),
 (569, 1),
 (570, 3),
 (571, 3),
 (572, 5),
 (573, 11),
 (574, 11),
 (575, 4),
 (576, 6),
 (577, 9),
 (578, 12),
 (579, 11),
 (580, 10),
 (581, 14),
 (582, 18),
 (583, 11),
 (584, 1),
 (585, 9),
 (586, 11),
 (587, 2),
 (588, 1),
 (589, 11),
 (590, 9),
 (591, 7),
 (592, 8),
 (593, 10),
 (594, 3),
 (595, 8),
 (596, 6),
 (597, 7),
 (598, 5),
 (599, 8),
 (600, 5),
 (601, 11),
 (602, 7),
 (603, 5),
 (604, 18),
 (605, 4),
 (606, 12),
 (607, 5),
 (608, 1),
 (609, 3),
 (610, 7),
 (611, 2),
 (612, 12),
 (613, 9),
 (614, 13)]

In [27]:
%%sql
SELECT album_id, COUNT(track_id) as album_track_num
    FROM album
    LEFT JOIN
    track 
    USING(album_id)
    GROUP BY album_id;

Done.

[(1, 10),
 (2, 1),
 (3, 3),
 (4, 8),
 (5, 15),
 (6, 13),
 (7, 12),
 (8, 14),
 (9, 8),
 (10, 14),
 (11, 12),
 (12, 12),
 (13, 8),
 (14, 13),
 (15, 5),
 (16, 7),
 (17, 10),
 (18, 17),
 (19, 11),
 (20, 11),
 (21, 18),
 (22, 3),
 (23, 34),
 (24, 23),
 (25, 13),
 (26, 17),
 (27, 14),
 (28, 10),
 (29, 14),
 (30, 14),
 (31, 9),
 (32, 14),
 (33, 17),
 (34, 17),
 (35, 11),
 (36, 17),
 (37, 20),
 (38, 12),
 (39, 21),
 (40, 12),
 (41, 14),
 (42, 14),
 (43, 7),
 (44, 6),
 (45, 14),
 (46, 13),
 (47, 14),
 (48, 13),
 (49, 10),
 (50, 4),
 (51, 22),
 (52, 15),
 (53, 14),
 (54, 20),
 (55, 20),
 (56, 15),
 (57, 15),
 (58, 9),
 (59, 7),
 (60, 7),
 (61, 11),
 (62, 7),
 (63, 12),
 (64, 9),
 (65, 9),
 (66, 10),
 (67, 16),
 (68, 9),
 (69, 13),
 (70, 13),
 (71, 14),
 (72, 18),
 (73, 30),
 (74, 12),
 (75, 14),
 (76, 15),
 (77, 11),
 (78, 14),
 (79, 10),
 (80, 10),
 (81, 11),
 (82, 13),
 (83, 24),
 (84, 16),
 (85, 14),
 (86, 15),
 (87, 3),
 (88, 12),
 (89, 13),
 (90, 12),
 (91, 16),
 (92, 14),
 (93, 13),
 (94, 11),
 (95, 12),
 (96, 11),
 (97, 10),
 (98, 11),
 (99, 12),
 (100, 9),
 (101, 10),
 (102, 18),
 (103, 10),
 (104, 10),
 (105, 10),
 (106, 9),
 (107, 8),
 (108, 10),
 (109, 9),
 (110, 8),
 (111, 8),
 (112, 8),
 (113, 11),
 (114, 8),
 (115, 20),
 (116, 10),
 (117, 11),
 (118, 11),
 (119, 13),
 (120, 17),
 (121, 10),
 (122, 14),
 (123, 12),
 (124, 14),
 (125, 16),
 (126, 15),
 (127, 10),
 (128, 8),
 (129, 8),
 (130, 7),
 (131, 8),
 (132, 9),
 (133, 9),
 (134, 10),
 (135, 9),
 (136, 7),
 (137, 5),
 (138, 4),
 (139, 15),
 (140, 16),
 (141, 57),
 (142, 14),
 (143, 14),
 (144, 10),
 (145, 18),
 (146, 18),
 (147, 10),
 (148, 12),
 (149, 16),
 (150, 10),
 (151, 14),
 (152, 8),
 (153, 13),
 (154, 8),
 (155, 11),
 (156, 9),
 (157, 14),
 (158, 13),
 (159, 13),
 (160, 15),
 (161, 12),
 (162, 17),
 (163, 17),
 (164, 12),
 (165, 15),
 (166, 14),
 (167, 21),
 (168, 12),
 (169, 16),
 (170, 1),
 (171, 2),
 (172, 1),
 (173, 2),
 (174, 14),
 (175, 12),
 (176, 14),
 (177, 10),
 (178, 16),
 (179, 13),
 (180, 15),
 (181, 11),
 (182, 12),
 (183, 9),
 (184, 16),
 (185, 17),
 (186, 11),
 (187, 11),
 (188, 11),
 (189, 14),
 (190, 16),
 (191, 10),
 (192, 14),
 (193, 17),
 (194, 16),
 (195, 15),
 (196, 14),
 (197, 8),
 (198, 6),
 (199, 12),
 (200, 11),
 (201, 16),
 (202, 18),
 (203, 17),
 (204, 9),
 (205, 10),
 (206, 12),
 (207, 11),
 (208, 7),
 (209, 10),
 (210, 9),
 (211, 18),
 (212, 12),
 (213, 18),
 (214, 11),
 (215, 14),
 (216, 12),
 (217, 14),
 (218, 15),
 (219, 15),
 (220, 11),
 (221, 20),
 (222, 15),
 (223, 15),
 (224, 22),
 (225, 16),
 (226, 1),
 (227, 19),
 (228, 23),
 (229, 26),
 (230, 25),
 (231, 24),
 (232, 12),
 (233, 11),
 (234, 15),
 (235, 11),
 (236, 12),
 (237, 17),
 (238, 14),
 (239, 10),
 (240, 10),
 (241, 14),
 (242, 12),
 (243, 17),
 (244, 11),
 (245, 12),
 (246, 13),
 (247, 15),
 (248, 19),
 (249, 6),
 (250, 22),
 (251, 25),
 (252, 1),
 (253, 24),
 (254, 1),
 (255, 23),
 (256, 12),
 (257, 12),
 (258, 19),
 (259, 17),
 (260, 1),
 (261, 17),
 (262, 2),
 (263, 2),
 (264, 2),
 (265, 2),
 (266, 1),
 (267, 1),
 (268, 1),
 (269, 10),
 (270, 14),
 (271, 14),
 (272, 1),
 (273, 1),
 (274, 1),
 (275, 1),
 (276, 1),
 (277, 1),
 (278, 1),
 (279, 1),
 (280, 2),
 (281, 1),
 (282, 1),
 (283, 1),
 (284, 1),
 (285, 1),
 (286, 1),
 (287, 1),
 (288, 1),
 (289, 1),
 (290, 1),
 (291, 1),
 (292, 1),
 (293, 1),
 (294, 1),
 (295, 1),
 (296, 1),
 (297, 1),
 (298, 1),
 (299, 1),
 (300, 1),
 (301, 1),
 (302, 1),
 (303, 1),
 (304, 1),
 (305, 1),
 (306, 1),
 (307, 1),
 (308, 1),
 (309, 1),
 (310, 1),
 (311, 1),
 (312, 1),
 (313, 1),
 (314, 2),
 (315, 1),
 (316, 1),
 (317, 1),
 (318, 1),
 (319, 1),
 (320, 1),
 (321, 12),
 (322, 11),
 (323, 1),
 (324, 1),
 (325, 1),
 (326, 1),
 (327, 1),
 (328, 1),
 (329, 1),
 (330, 1),
 (331, 1),
 (332, 1),
 (333, 1),
 (334, 1),
 (335, 1),
 (336, 1),
 (337, 1),
 (338, 1),
 (339, 1),
 (340, 1),
 (341, 1),
 (342, 1),
 (343, 1),
 (344, 1),
 (345, 1),
 (346, 1),
 (347, 1)]

In [45]:
%%sql
With invoice_track AS
(
SELECT a.invoice_id, b.album_id, COUNT(DISTINCT a.track_id) AS invoice_track_num
    FROM invoice_line a
    INNER JOIN 
    track b
    USING(track_id)
    GROUP BY a.invoice_id, b.album_id
),
album_track AS
(
    SELECT album_id, COUNT(track_id) as album_track_num
    FROM album
    LEFT JOIN
    track 
    USING(album_id)
    GROUP BY album_id
),
purchase AS
(
    SELECT CASE WHEN album_track_num = invoice_track_num THEN "Full album"
    ELSE "Individual track" END AS purchase_type,
    invoice_id
    FROM album_track 
    LEFT JOIN
    invoice_track
    USING(album_id)
)
SELECT purchase_type , COUNT(DISTINCT invoice_id) AS invoice_num,
CAST(COUNT(DISTINCT invoice_id) AS float)*100/(SELECT COUNT( DISTINCT invoice_id) FROM purchase) AS pert_of_invoice
FROM purchase
GROUP BY purchase_type;

Done.

[('Full album', 201, 32.73615635179153),
 ('Individual track', 500, 81.43322475570032)]

Most of the purchase made were individual track purchase. So it is better to change our strategry of focusing on selling the top popular tracks from the given album than the whole list of tracks for that albu,

### Which artist is used in the most playlists?

In [65]:
%%sql
WITH playlist_info AS
(
    SELECT a.playlist_id, a.name, b.track_id
    FROM playlist a 
    LEFT JOIN 
    playlist_track b
    USING(playlist_id)
),
artist_info AS
(
    SELECT a.artist_id, a.name, b.album_id
    FROM artist a
    LEFT JOIN
    album b 
    USING(artist_id)
),
all_info AS
(
    SELECT a.name AS playlist, b.name AS artist, c.track_id
    FROM playlist_info a
    LEFT JOIN 
    track c
    ON a.track_id = c.track_id
    LEFT JOIN artist_info b
    ON
    b.album_id = c.album_id
    
)
SELECT artist, COUNT(distinct playlist) AS num_times_artist_present,
COUNT(playlist) as num_of_features
    FROM all_info
    GROUP BY artist
    ORDER BY num_times_artist_present DESC;

Done.

[('Eugene Ormandy', 6, 15),
 ('Academy of St. Martin in the Fields & Sir Neville Marriner', 5, 10),
 ('Berliner Philharmoniker & Herbert Von Karajan', 5, 13),
 ('English Concert & Trevor Pinnock', 5, 9),
 ("The King's Singers", 5, 10),
 ('Academy of St. Martin in the Fields, Sir Neville Marriner & Thurston Dart', 4, 5),
 ('Adrian Leaper & Doreen de Feis', 4, 5),
 ('Alberto Turco & Nova Schola Gregoriana', 4, 5),
 ('Antal Doráti & London Symphony Orchestra', 4, 5),
 ('Barry Wordsworth & BBC Concert Orchestra', 4, 5),
 ('Berliner Philharmoniker & Hans Rosbaud', 4, 5),
 ('Boston Symphony Orchestra & Seiji Ozawa', 4, 5),
 ('Britten Sinfonia, Ivor Bolton & Lesley Garrett', 4, 5),
 ('Chicago Symphony Chorus, Chicago Symphony Orchestra & Sir Georg Solti', 4, 5),
 ('Chicago Symphony Orchestra & Fritz Reiner', 4, 5),
 ('Chor der Wiener Staatsoper, Herbert Von Karajan & Wiener Philharmoniker', 4, 5),
 ('Emanuel Ax, Eugene Ormandy & Philadelphia Orchestra', 4, 5),
 ('Gustav Mahler', 4, 5),
 ('James Levine', 4, 5),
 ('Julian Bream', 4, 5),
 ("Kent Nagano and Orchestre de l'Opéra de Lyon", 4, 5),
 ('Luciano Pavarotti', 4, 5),
 ('Martin Roscoe', 4, 5),
 ('Maurizio Pollini', 4, 5),
 ('Mela Tenenbaum, Pro Musica Prague & Richard Kapp', 4, 5),
 ('Michael Tilson Thomas & San Francisco Symphony', 4, 10),
 ('Orchestre Révolutionnaire et Romantique & John Eliot Gardiner', 4, 5),
 ('Philharmonia Orchestra & Sir Neville Marriner', 4, 5),
 ('Philip Glass Ensemble', 4, 5),
 ('Richard Marlow & The Choir of Trinity College, Cambridge', 4, 5),
 ('Scholars Baroque Ensemble', 4, 5),
 ('Sir Georg Solti & Wiener Philharmoniker', 4, 5),
 ('Sir Georg Solti, Sumi Jo & Wiener Philharmoniker', 4, 5),
 ('Ton Koopman', 4, 5),
 ('Wilhelm Kempff', 4, 5),
 ('Yo-Yo Ma', 4, 5),
 ('Aaron Copland & London Symphony Orchestra', 3, 4),
 ('Academy of St. Martin in the Fields Chamber Ensemble & Sir Neville Marriner', 3, 4),
 ('Academy of St. Martin in the Fields, John Birch, Sir Neville Marriner & Sylvia McNair', 3, 4),
 ('Accept', 3, 15),
 ('Alice In Chains', 3, 37),
 ('Anne-Sophie Mutter, Herbert Von Karajan & Wiener Philharmoniker', 3, 4),
 ('Berliner Philharmoniker, Claudio Abbado & Sabine Meyer', 3, 4),
 ('C. Monteverdi, Nigel Rogers - Chiaroscuro; London Baroque; London Cornett & Sackbu', 3, 4),
 ('Caetano Veloso', 3, 63),
 ("Charles Dutoit & L'Orchestre Symphonique de Montréal", 3, 4),
 ('Chico Buarque', 3, 87),
 ('Choir Of Westminster Abbey & Simon Preston', 3, 4),
 ("Christopher O'Riley", 3, 4),
 ('Djavan', 3, 83),
 ('Edo de Waart & San Francisco Symphony', 3, 4),
 ('Emerson String Quartet', 3, 4),
 ('Equale Brass Ensemble, John Eliot Gardiner & Munich Monteverdi Orchestra and Choir', 3, 4),
 ('Eric Clapton', 3, 145),
 ('Felix Schmidt, London Symphony Orchestra & Rafael Frühbeck de Burgos', 3, 4),
 ('Fretwork', 3, 4),
 ('Gerald Moore', 3, 4),
 ('Gilberto Gil', 3, 82),
 ('Gonzaguinha', 3, 44),
 ('Göteborgs Symfoniker & Neeme Järvi', 3, 4),
 ('Herbert Von Karajan, Mirella Freni & Wiener Philharmoniker', 3, 4),
 ('Hilary Hahn, Jeffrey Kahane, Los Angeles Chamber Orchestra & Margaret Batjer', 3, 4),
 ('Iron Maiden', 3, 516),
 ('Itzhak Perlman', 3, 4),
 ('Leonard Bernstein & New York Philharmonic', 3, 4),
 ('Les Arts Florissants & William Christie', 3, 4),
 ('London Symphony Orchestra & Sir Charles Mackerras', 3, 4),
 ('Metallica', 3, 296),
 ('Michele Campanella', 3, 4),
 ('Mötley Crüe', 3, 52),
 ('Nash Ensemble', 3, 4),
 ('Nirvana', 3, 93),
 ('Orchestra of The Age of Enlightenment', 3, 4),
 ('Otto Klemperer & Philharmonia Orchestra', 3, 4),
 ('Ozzy Osbourne', 3, 79),
 ('Pearl Jam', 3, 177),
 ('Roger Norrington, London Classical Players', 3, 4),
 ('Royal Philharmonic Orchestra & Sir Thomas Beecham', 3, 4),
 ('Sergei Prokofiev & Yuri Temirkanov', 3, 4),
 ('Soundgarden', 3, 49),
 ('Stone Temple Pilots', 3, 37),
 ('Temple of the Dog', 3, 31),
 ('The 12 Cellists of The Berlin Philharmonic', 3, 4),
 ('Yehudi Menuhin', 3, 4),
 (None, 2, 4),
 ('AC/DC', 2, 37),
 ('Aerosmith', 2, 45),
 ('Alanis Morissette', 2, 39),
 ('Antônio Carlos Jobim', 2, 64),
 ('Apocalyptica', 2, 24),
 ('Audioslave', 2, 81),
 ('BackBeat', 2, 36),
 ('Black Sabbath', 2, 36),
 ('Body Count', 2, 51),
 ('Bruce Dickinson', 2, 33),
 ('Chico Science & Nação Zumbi', 2, 108),
 ('Cidade Negra', 2, 76),
 ('Cássia Eller', 2, 62),
 ('Deep Purple', 2, 226),
 ('Def Leppard', 2, 48),
 ('Dread Zeppelin', 2, 3),
 ('Ed Motta', 2, 42),
 ('Elis Regina', 2, 31),
 ('Faith No More', 2, 145),
 ('Falamansa', 2, 33),
 ('Foo Fighters', 2, 101),
 ('Funk Como Le Gusta', 2, 48),
 ('Green Day', 2, 83),
 ("Guns N' Roses", 2, 114),
 ('Habib Koité and Bamada', 2, 6),
 ('House Of Pain', 2, 57),
 ('Incognito', 2, 39),
 ('James Brown', 2, 60),
 ('Jamiroquai', 2, 96),
 ('Joe Satriani', 2, 30),
 ('Jorge Ben', 2, 31),
 ('Jota Quest', 2, 36),
 ('Judas Priest', 2, 33),
 ('Kiss', 2, 104),
 ('Led Zeppelin', 2, 252),
 ('Legião Urbana', 2, 93),
 ('Lenny Kravitz', 2, 143),
 ('Miles Davis', 2, 75),
 ('Milton Nascimento', 2, 55),
 ('Motörhead', 2, 32),
 ('Nicolaus Esterhazy Sinfonia', 2, 3),
 ('Os Paralamas Do Sucesso', 2, 119),
 ('Page & Plant', 2, 36),
 ('Passengers', 2, 42),
 ('Planet Hemp', 2, 48),
 ('Queen', 2, 94),
 ('R.E.M.', 2, 96),
 ('R.E.M. Feat. Kate Pearson', 2, 33),
 ('Raimundos', 2, 30),
 ('Red Hot Chili Peppers', 2, 128),
 ('Rush', 2, 42),
 ('Santana', 2, 75),
 ('Scorpions', 2, 25),
 ('Skank', 2, 57),
 ('Smashing Pumpkins', 2, 85),
 ('Spyro Gyra', 2, 54),
 ('Terry Bozzio, Tony Levin & Steve Stevens', 2, 21),
 ('The Clash', 2, 54),
 ('The Cult', 2, 64),
 ('The Police', 2, 42),
 ('The Rolling Stones', 2, 111),
 ('The Tea Party', 2, 76),
 ('Tim Maia', 2, 67),
 ('Titãs', 2, 114),
 ('U2', 2, 333),
 ('UB40', 2, 42),
 ('Van Halen', 2, 122),
 ('Zeca Pagodinho', 2, 57),
 ('Aaron Goldberg', 1, 2),
 ('Aisha Duo', 1, 4),
 ('Amy Winehouse', 1, 46),
 ('Aquaman', 1, 2),
 ('Battlestar Galactica', 1, 40),
 ('Battlestar Galactica (Classic)', 1, 48),
 ('Billy Cobham', 1, 16),
 ('Black Label Society', 1, 36),
 ('Buddy Guy', 1, 22),
 ('Cake', 1, 2),
 ('Calexico', 1, 2),
 ('Chris Cornell', 1, 28),
 ('Cláudio Zoli', 1, 20),
 ('Creedence Clearwater Revival', 1, 80),
 ('David Coverdale', 1, 24),
 ('Dennis Chambers', 1, 18),
 ('Frank Sinatra', 1, 48),
 ('Frank Zappa & Captain Beefheart', 1, 18),
 ('Gene Krupa', 1, 44),
 ('Godsmack', 1, 24),
 ('Heroes', 1, 46),
 ('JET', 1, 26),
 ('Jimi Hendrix', 1, 34),
 ('João Suplicy', 1, 28),
 ('Karsh Kale', 1, 4),
 ('Lost', 1, 184),
 ('Luciana Souza/Romero Lubambo', 1, 2),
 ('Lulu Santos', 1, 56),
 ('Marcos Valle', 1, 34),
 ('Marillion', 1, 20),
 ('Marisa Monte', 1, 36),
 ('Marvin Gaye', 1, 36),
 ('Men At Work', 1, 20),
 ('Mônica Marianno', 1, 24),
 ('O Rappa', 1, 34),
 ('O Terço', 1, 30),
 ('Olodum', 1, 28),
 ('Os Mutantes', 1, 28),
 ("Paul D'Ianno", 1, 20),
 ('Pink Floyd', 1, 18),
 ('Raul Seixas', 1, 28),
 ('Stevie Ray Vaughan & Double Trouble', 1, 20),
 ('System Of A Down', 1, 22),
 ('The Black Crowes', 1, 38),
 ('The Doors', 1, 22),
 ('The Office', 1, 106),
 ('The Posies', 1, 4),
 ('The Who', 1, 40),
 ('Toquinho & Vinícius', 1, 30),
 ('Various Artists', 1, 112),
 ('Velvet Revolver', 1, 26),
 ('Vinícius De Moraes', 1, 30)]

Eugene Ormandy is present inthe most playlist but this doesn't account for the popularity. Iron maiden though present in less number of playlist has the highest number of songs present. This might be due to the generation gap where younger people have more songs of iron maiden.

### How many tracks have been purchased vs not purchased?

In [70]:
%%sql 
WITH track_info AS
(SELECT track.track_id as album_track, 
    i.track_id  as invoice_track
    FROM track
    LEFT JOIN
(    
    SELECT DISTINCT track_id
    FROM invoice
    LEFT JOIN
    invoice_line
    USING(invoice_id)
) i
USING(track_id)),
purchase AS
(
    SELECT
    CASE WHEN album_track = invoice_track then "Purchased"
    ELSE "Not purchased" END as track_status
    FROM track_info
)
SELECT track_status, 
        COUNT(track_status) AS num_track
FROM purchase
GROUP BY track_status;

Done.

[('Not purchased', 1697), ('Purchased', 1806)]

### Is the range of tracks in the store reflective of their sales popularity?

In [76]:
%%sql
SELECT genre.name AS track_range, count(genre.name) AS num_tracks
    FROM track
    LEFT JOIN
    genre
    USING(genre_id)
    GROUP BY genre.name
    ORDER BY num_tracks DESC;

Done.

[('Rock', 1297),
 ('Latin', 579),
 ('Metal', 374),
 ('Alternative & Punk', 332),
 ('Jazz', 130),
 ('TV Shows', 93),
 ('Blues', 81),
 ('Classical', 74),
 ('Drama', 64),
 ('R&B/Soul', 61),
 ('Reggae', 58),
 ('Pop', 48),
 ('Soundtrack', 43),
 ('Alternative', 40),
 ('Hip Hop/Rap', 35),
 ('Electronica/Dance', 30),
 ('Heavy Metal', 28),
 ('World', 28),
 ('Sci Fi & Fantasy', 26),
 ('Easy Listening', 24),
 ('Comedy', 17),
 ('Bossa Nova', 15),
 ('Science Fiction', 13),
 ('Rock And Roll', 12),
 ('Opera', 1)]

Rock, Metal and Latin are the 3 genres for which we have more tracks in the store

In [86]:
%%sql
SELECT genre.name as genre_type,
        SUM(invoice.total) AS total_sales,
        SUM(invoice.total)/COUNT(invoice_line.track_id) AS sales_per_track,
        COUNT(DISTINCT invoice_line.track_id) AS track_sold,
        COUNT(track.track_id) AS total_tracks



    FROM track 
    LEFT JOIN invoice_line
    USING(track_id)
    LEFT JOIN invoice
    USING(invoice_id)
    LEFT JOIN genre
    USING(genre_id)
    GROUP BY genre.name
    ORDER BY sales_per_track DESC;

Done.

[('Hip Hop/Rap', 463.32000000000005, 14.040000000000001, 21, 47),
 ('Easy Listening', 951.3899999999994, 12.856621621621613, 24, 74),
 ('Electronica/Dance', 614.7899999999998, 11.177999999999997, 29, 56),
 ('Blues', 1379.0700000000038, 11.121532258064546, 56, 149),
 ('R&B/Soul', 1751.310000000005, 11.014528301886823, 55, 165),
 ('Jazz', 1302.8400000000004, 10.767272727272731, 61, 190),
 ('Latin', 1705.770000000001, 10.214191616766472, 119, 627),
 ('Rock', 26751.77999999988, 10.152478178368076, 915, 3017),
 ('TV Shows', 19.8, 9.9, 2, 93),
 ('Alternative & Punk', 4841.099999999979, 9.839634146341421, 176, 648),
 ('Alternative', 1095.9300000000005, 9.366923076923081, 34, 123),
 ('Soundtrack', 46.529999999999994, 9.306, 5, 43),
 ('Pop', 568.2599999999998, 9.019999999999996, 25, 86),
 ('Heavy Metal', 70.29, 8.78625, 7, 29),
 ('Metal', 5316.299999999997, 8.588529886914374, 238, 755),
 ('Classical', 361.3499999999999, 7.688297872340423, 16, 105),
 ('Reggae', 257.40000000000003, 7.354285714285715, 22, 71),
 ('Drama', 5.9399999999999995, 5.9399999999999995, 1, 64),
 ('Bossa Nova', None, None, 0, 15),
 ('Comedy', None, None, 0, 17),
 ('Opera', None, None, 0, 1),
 ('Rock And Roll', None, None, 0, 12),
 ('Sci Fi & Fantasy', None, None, 0, 26),
 ('Science Fiction', None, None, 0, 13),
 ('World', None, None, 0, 28)]

Most sales are coming from the HIP/HOP. So we should have more of the popular genres in the store. Also some of the genres have been unsold at all. So such genres track should not be restocked.